trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - 'tools/*'
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - ISSUES.md
    - LICENSE
    - NOTICE
    - README.md
    - SECURITY.md

stages:
- stage: adapter
  displayName: 'adapter'
  jobs:
  - job: build
    displayName: 'Build SEAL-Embedded test image'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: CMake@1
      displayName: 'CMake SEAL-Embedded Adapter'
      inputs:
        workingDirectory: '$(Build.SourcesDirectory)/build-adapter'
        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release ../adapter'
    - task: MSBuild@1
      displayName: 'Build SEAL-Embedded Adapter'
      inputs:
        solution: '$(Build.SourcesDirectory)/build-adapter/seal_embedded_adapter.sln'
        msbuildArchitecture: 'x64'
        platform: 'x64'
        configuration: 'Release'
    - task: CmdLine@2
      displayName: 'Run SEAL-Embedded Adapter'
      inputs:
        script: |
          echo 1 >> test.txt
          $(Build.SourcesDirectory)/build-adapter/bin/Release/se_adapter.exe < test.txt
#    - task: CMake@1
#      displayName: 'CMake SEAL-Embedded'
#      inputs:
#        workingDirectory: '$(Build.SourcesDirectory)/build-device'
#        cmakeArgs: '-DCMAKE_BUILD_TYPE=Release -DSE_BUILD_LOCAL=ON -DSE_BUILD_M4=OFF -DSE_M4_IS_SPHERE=OFF -DSE_BUILD_TYPE="Tests" ../device'
#    - task: MSBuild@1
#      displayName: 'Build SEAL-Embedded'
#      inputs:
#        solution: '$(Build.SourcesDirectory)/build-device/seal_embedded.sln'
#        msbuildArchitecture: 'x64'
#        platform: 'x64'
#        configuration: 'Release'
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2
      displayName: 'Run CredScan'
      inputs:
        toolMajorVersion: 'V2'
        outputFormat: sarif
        debugMode: false
    - task: securedevelopmentteam.vss-secure-development-tools.build-task-roslynanalyzers.RoslynAnalyzers@2
      displayName: 'Run Roslyn Analyzers'
    - task: Semmle@0
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      inputs:
        sourceCodeDirectory: '$(Build.SourcesDirectory)'
        language: 'cpp'
        includeNodeModules: true
        querySuite: 'Recommended'
        timeout: '1800'
        ram: '16384'
        addProjectDirToScanningExclusionList: true
        buildCommands: '"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat" && msbuild $(Build.SourcesDirectory)/build-adapter/seal_embedded_adapter.sln'
        cleanupBuildCommands: '"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat" && msbuild $(Build.SourcesDirectory)/build-adapter/seal_embedded_adapter.sln /t:Clean'
    - task: ComponentGovernanceComponentDetection@0
      inputs:
        scanType: 'Register'
        verbosity: 'Verbose'
        alertWarningLevel: 'High'
    - task: PublishSecurityAnalysisLogs@2
      inputs:
        ArtifactName: 'CodeAnalysisLogs'
        ArtifactType: 'Container'
        AllTools: true
        ToolLogsNotFoundAction: 'Standard'
